### ISSUE TITLE
[Panic] Can not start if use event release

### ISSUE THREAD

**Issue by haunt98** [orhun/daktilo#33]
**Describe the bug**

**To reproduce**

- `cargo install --locked daktilo`
- Use this [mp3 from nathan-fiscaletti/keyboardsounds](https://github.com/nathan-fiscaletti/keyboardsounds/blob/master/keyboardsounds/profiles/holy-panda/release_key.mp3)
- Use following config:

```toml
[[sound_preset]]
name = "holy_panda"
key_config = [
  { event = "press", keys = "Return", files = [
    { path = "/Users/XXX/go/src/github.com/nathan-fiscaletti/keyboardsounds/keyboardsounds/profiles/holy-panda/press_enter.mp3", volume = 2.0 },
  ] },
  { event = "press", keys = "Backspace", files = [
    { path = "/Users/XXX(/go/src/github.com/nathan-fiscaletti/keyboardsounds/keyboardsounds/profiles/holy-panda/press_back.mp3", volume = 2.0 },
  ] },
  { event = "press", keys = "Space", files = [
    { path = "/Users/XXX/go/src/github.com/nathan-fiscaletti/keyboardsounds/keyboardsounds/profiles/holy-panda/press_space.mp3", volume = 2.0 },
  ] },
  { event = "press", keys = ".*", files = [
    { path = "/Users/XXX/go/src/github.com/nathan-fiscaletti/keyboardsounds/keyboardsounds/profiles/holy-panda/press_key1.mp3", volume = 2.0 },
    { path = "/Users/XXX/go/src/github.com/nathan-fiscaletti/keyboardsounds/keyboardsounds/profiles/holy-panda/press_key2.mp3", volume = 2.0 },
    { path = "/Users/XXX/go/src/github.com/nathan-fiscaletti/keyboardsounds/keyboardsounds/profiles/holy-panda/press_key3.mp3", volume = 2.0 },
    { path = "/Users/XXX/go/src/github.com/nathan-fiscaletti/keyboardsounds/keyboardsounds/profiles/holy-panda/press_key4.mp3", volume = 2.0 },
    { path = "/Users/XXX/go/src/github.com/nathan-fiscaletti/keyboardsounds/keyboardsounds/profiles/holy-panda/press_key5.mp3", volume = 2.0 },
  ], strategy = "random" },
  { event = "release", keys = ".*", files = [
    { path = "/Users/XXX/go/src/github.com/nathan-fiscaletti/keyboardsounds/keyboardsounds/profiles/holy-panda/release_key.mp3", volume = 1.0 },
  ] },
]
```

**Expected behavior**

It starts nomarlly

**Screenshots / Logs**

```
➜  ~ RUST_BACKTRACE=full daktilo --preset holy_panda
2023-10-05T02:44:44.555053Z  INFO daktilo: Starting...
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/XXX/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rodio-0.17.1/src/decoder/symphonia.rs:175:22
stack backtrace:
   0:        0x102ff89a8 - __mh_execute_header
   1:        0x102ec811c - __mh_execute_header
   2:        0x102fd92a0 - __mh_execute_header
   3:        0x102ffc144 - __mh_execute_header
   4:        0x102ffbd7c - __mh_execute_header
   5:        0x102ffcc68 - __mh_execute_header
   6:        0x102ffc7e0 - __mh_execute_header
   7:        0x102ffc754 - __mh_execute_header
   8:        0x102ffc748 - __mh_execute_header
   9:        0x103062638 - __mh_execute_header
  10:        0x103062688 - __mh_execute_header
  11:        0x102f07180 - __mh_execute_header
  12:        0x102f05e44 - __mh_execute_header
  13:        0x102f00040 - __mh_execute_header
  14:        0x102effc84 - __mh_execute_header
  15:        0x102eff4d4 - __mh_execute_header
  16:        0x102fcb5d4 - __mh_execute_header
  17:        0x102fcbb40 - __mh_execute_header
  18:        0x10339a7ac - _DefaultOutputAUFactory
  19:        0x1034999dc - _AUNotQuiteSoSimpleTimeFactory
  20:        0x10339eb58 - _AUGenericOutputFactory
  21:        0x183a110b0 - <unknown>
  22:        0x183a0e4e0 - <unknown>
  23:        0x183b97cb8 - <unknown>
  24:        0x1811f7034 - __pthread_joiner_wake
fatal runtime error: Rust panics must be rethrown
[1]    92809 abort      RUST_BACKTRACE=full daktilo --preset holy_panda
```

**Software information**

- Operating system: macOS 14.0
- Rust version: rustc 1.72.1 (d5c2e9c34 2023-09-13)
- Project version: 0.2.0

**Additional context**

Only this mp3 is error, another mp3 plays fine. I don't use Rust but as I read logs, it seems the panic in the lib rodio 0.17.1.

**Comment by orhun** [comment]
Thanks for reporting this! 🐻 

I am able to reproduce:

```
thread 'cpal_alsa_out' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/orhun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rodio-0.17.1/src/decoder/symphonia.rs:175:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I guess something is wrong with that MP3 file. Feel free to re-encode it and try that new file.

Also, it would be nice to report this to [`rodio`](https://github.com/RustAudio/rodio) or [`Symphonia`](https://github.com/pdeljanov/Symphonia). There isn't much that I can do on the`daktilo` side for this.

**Comment by haunt98** [comment]
Thanks @orhun, maybe bad mp3 👍
